### ISSUE TITLE
[Cosmetic Bug] no clear feedback if selected channel is "------"

### ISSUE THREAD

**Issue by yvesg54** [tunisiano187/WME-send-to-slack#31]
I previously made a mistake, and configured "---" as channel.
Later, when attempting to generate a slack message, the script flatly refused to generate it, but did not explain why.

**Comment by ordonezgs** [comment]
Hello,

Please provide an example image. I'm not able to reproduce: I'm not able even to select a "---" channel.

<img width="330" alt="Captura de Pantalla 2020-07-22 a la(s) 3 30 34 p  m" src="https://user-images.githubusercontent.com/17103864/88225618-6a2c3500-cc30-11ea-8042-ab9793c3c073.png">

**Comment by tunisiano187** [comment]
In the country list

Le mer. 22 juil. 2020 à 22:32, ordonezgs <notifications@github.com> a
écrit :

**Comment by yvesg54** [comment]
If you select country=belgium, you have a "----" channel.

**Comment by ordonezgs** [comment]
Thank you for your report. This wasn't a cosmetical bug, actually you have found a bug.

The WazeWrap is generating an error in the CheckNeededParams() function, which is intended to alert the script user if there are any missing configuration parameters, the user wasn't being alerted due to the error in the alert thing. This was closely related to #29 .

I will push a fix to change the alert from WazeWrap to the normal browser alert as a temporary solution in case of any missing settings.

> Uncaught TypeError: t.message.replace is not a function
    at p (toastr.js:473)
    at s (toastr.js:341)
    at C (toastr.js:296)
    at Object.t [as error] (toastr.js:53)
    at Alerts.error (WazeWrapLib.js?_=1595472921668:2053)
    at CheckNeededParams (userscript.html?name=WME%20Send%20to%20Slack.user.js&id=feacac6c-8c1b-4639-96fd-789c13f88b52:1026)
    at HTMLImageElement.eval (userscript.html?name=WME%20Send%20to%20Slack.user.js&id=feacac6c-8c1b-4639-96fd-789c13f88b52:707)
    at HTMLDocument.dispatch (vendor-9a07eafd83ccc30838d5.js:1)
    at HTMLDocument.f.handle (vendor-9a07eafd83ccc30838d5.js:1)

Since the WazeWrap load is finished first in the 2020.07.22.01 I have no clue what can be causing this error.

**Comment by ordonezgs** [comment]
The problem was in the Google Spreadsheets API response creating another array. The fix is out. Please update to the latest version.

Fixed...

Thanks for your report.
