### ISSUE TITLE
[Bug] STS not compatible with the latest beta version of WME

### ISSUE THREAD

**Issue by yvesg54** [tunisiano187/WME-send-to-slack#61]
Glodenox fixed a similar issue in WME Open Maps.

**Comment by ordonezgs** [comment]
Working on this. A pull request was opened. Thanks for the info @yvesg54

**Comment by ordonezgs** [comment]
Seems to be fixed, please comment if the issue persists.

**Comment by yvesg54** [comment]
It had been fixed, but problem is back, same symptoms, same entries in console log.
WME 2.1.159.0-57451efe v2.72-94-ge8034dd72
STS 2021.02.19.01

**Comment by ordonezgs** [comment]
@yvesg54 Please open editor. Then open console, and reload the page, after that (It doesn't matter if the site have already or if is it loading). Paste this code into the console.
`do{
if (typeof W === 'undefined'){
    console.error("WMESTS Error.... W UNDEFINED");
}
if(typeof W.map === 'undefined'){
    console.error("WMESTS Error.... W.map UNDEFINED");
}
if(typeof W.prefs === 'undefined'){
    console.error("WMESTS Error.... W.prefs UNDEFINED")
}
if(document.getElementById('edit-panel') === null){
    console.error("WMESTS Error.... EDIT PANEL NOT READY")
}
if(WazeWrap.Ready != true){
    console.error("WMESTS Error.... WazeWrap Not Ready")
}
if(((window.location.href.indexOf("segment") > -1) && document.getElementById('unpavedCheckbox') === null)){
    console.error("WMESTS Error.... Segments and Checkbox Still not returning NULL")
}
console.warning("Running WMESTS check undefinitively")
}while(true);` 

And press enter to run it.

Please pay attention now to the Red Error console messages with title WMESTS Error... and paste it here, try to not repeat the messages which are equal, because of the proccess it will try to check any time at any moment.

Or even any other red message which says "Uncaught ReferenceError:" after running this code. Help is appreciated to debug this. Thank you.

**Comment by yvesg54** [comment]
Now I cannot reproduce the problem...
STS works well again.
I will run the debug code it it occurs again.  I tested the code, I had to replace "warning" by "warn".  It does not display any error (as expected, as the problem was not visible).
Sorry.

**Comment by ordonezgs** [comment]
It seems to be a WazeWrap issue, so it should work fine now. 👍

Enviado desde mi iPhone

El 20/02/2021, a la(s) 12:25 p. m., yvesg54 <notifications@github.com> escribió:

﻿

Now I cannot reproduce the problem...
STS works well again.
I will run the debug code it it occurs again. I tested the code, I had to replace "warning" by "warn". It does not display any error (as expected, as the problem was not visible).
Sorry.

**Comment by yvesg54** [comment]
So I got a new version of WazeWrap without noticing it?

**Comment by ordonezgs** [comment]
Yes. WazeWrap isn't a installed script; rather it is an script which is called from many installed scripts to work with. So, each time you use a script that uses WazeWrap it asks for the newer version without requiring an update from the user.

I must say, that WazeWrap is managed from WazeDev team (community team), so it is out of control of WME Send to Slack script maintainers.

The issue was associated with WazeWrap due to an unready call from the library, so the script (WMESTS) wasn't able to work so.
