### ISSUE TITLE
Settings Tab Missing, in 2022.08.15.01 workaround found

### ISSUE THREAD

**Issue by grosshad** [tunisiano187/WME-send-to-slack#90]
> Hi @tunisiano187 ,
> 
> I found that settings icon and tab not work because is needed to update the selectors in lines 774 and 775, please try this:
> 
> ```js
> $(".tabs-container ul.nav.nav-tabs").append(b);
> $(".contents .tab-content").append('<div class="tab-pane" id="segment-edit-settings"><div class="settings">Slack</div></div>');
> ```
> 
> replace as this:
> 
> ```js
> $("#user-info .flex-parent #user-tabs .nav-tabs").append(b);
> $("#user-info .flex-parent .tab-content").append('<div class="tab-pane" id="segment-edit-settings"><div class="settings">Slack</div></div>');
> ```
> 
> Other issue I got was that jQuery selectors not work if `$` variable is not declared globally, so, in this case I did it by putting following after the UserScript section (line 28), and everything works well.
> 
> ```js
> /* global $ */
> ```

with version 2022.08.15.01 this patch need to be applied to lines 744 and 745

_Originally posted by @grosshad in https://github.com/tunisiano187/WME-send-to-slack/issues/84#issuecomment-1309103854_

**Comment by ordonezgs** [comment]
There are two issues with the proposed solution:

* When you select the button it happens nothing.
* The button only appears after selecting and de-selecting the segment.

![image](https://user-images.githubusercontent.com/17103864/201206430-538a12ff-4241-41cf-9442-70d128ef43c4.png)

About UI, the thing is that Tunisiano has set the button in the segment tabs rather than in the dashboard of WME.

**Comment by tunisiano187** [comment]
@ordonezgs, that's not a problem, it was the easiest way at that time, but if we have a solution now, i'm not the only user of the script, the most important is that the editors can use it.
I'm sorry, but i'm still really busy at home, so i stll can't help here for some time.
Don't hesitate to update it like you want, the only condition is that it need to meet the majority of editors's needs ;-)

**Comment by ordonezgs** [comment]
> @ordonezgs, that's not a problem, it was the easiest way at that time, but if we have a solution now, i'm not the only user of the script, the most important is that the editors can use it. I'm sorry, but i'm still really busy at home, so i stll can't help here for some time. Don't hesitate to update it like you want, the only condition is that it need to meet the majority of editors's needs ;-)

No problem. I'm unable to work on it. I do have time now, but at the moment still don´t know how to fix this since I don't fully understand the WME UI.

Another thing is that it will be problematic trying to propose a solution over there, since the Staff is now planning to re-design that tab, the issue tracker.

![image](https://user-images.githubusercontent.com/17103864/201550444-b511d4cf-2939-481a-8675-b9cf2862510b.png)

More info at: https://www.waze.com/forum/viewtopic.php?t=363475&view=unread#unread

**Comment by ordonezgs** [comment]
Any way, a lot of thanks for your contribution @grosshad . Please let us know if you can handle to work this.
